name: CI Pipeline

# Run on every push or PR to main branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup NodeJS (use version you used locally, e.g. 18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (if you have tests configured)
      - name: Run tests
        run: npm test --if-present

      # 5. Build the project
      - name: Build project
        run: npm run build --if-present

      # 6. (Optional) Upload build output as artifact
      - name: Upload production-ready build
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build
